import { getOAuthToken } from "./auth";
import { sleep, parseListUnsubscribeHeader } from "./utils";
import { UnsubscribeData } from "../types/types";

export async function getMultipleUnsubscribeData(
  messageIds: string[]
): Promise<UnsubscribeData[]> {
  const token: chrome.identity.GetAuthTokenResult = await getOAuthToken();
  const unsubscribeData: UnsubscribeData[] = [];

  for (const messageId of messageIds) {
    const data = await getUnsubscribeData(messageId, token);
    unsubscribeData.push(data);
  }

  return unsubscribeData;
}

export async function getUnsubscribeData(
  messageId: string,
  token: any
): Promise<UnsubscribeData> {
  const headerData: UnsubscribeData = await getListUnsubscribeHeader(
    messageId,
    token
  );

  // Return if we have some unsubscribe data from the headers
  if (headerData.posturl || headerData.mailto) {
    return headerData;
  }

  // If no unsubscribe data found in headers, look for a link in the email body
  const unsubscribeLink = await getUnsubscribeLinkFromBody(messageId, token);
  return { posturl: headerData.posturl, mailto: headerData.mailto, clickurl: unsubscribeLink };
}

export async function getListUnsubscribeHeader(
  messageId: string,
  token: any
): Promise<UnsubscribeData> {
  // Get the List-Unsubscribe header for a specific message
  const url = `https://www.googleapis.com/gmail/v1/users/me/messages/${messageId}?format=metadata&metadataHeaders=List-Unsubscribe`;
  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
  });

  // Handle rate limiting
  if (response.status === 429) {
    console.warn("Rate limit hit. Pausing...");
    await sleep(1000);
    return await getListUnsubscribeHeader(token, messageId); // Retry
  }

  // Get the List-Unsubscribe header from the response
  const data = await response.json();
  const header = data.payload?.headers?.find(
    (header: { name: string }) => header.name === "List-Unsubscribe"
  )?.value;

  // Parse the List-Unsubscribe header and return the data
  const parsedHeader = parseListUnsubscribeHeader(header);
  return parsedHeader;
}

export async function getUnsubscribeLinkFromBody(
  messageId: string,
  token: any
): Promise<string | null> {
  const url = `https://www.googleapis.com/gmail/v1/users/me/messages/${messageId}?format=full`;
  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
  });

  if (response.status === 429) {
    console.warn("Rate limit hit. Pausing...");
    await sleep(1000);
    return await getUnsubscribeLinkFromBody(messageId, token); // Retry
  }

  const data = await response.json();
  const body = data.payload?.parts?.find(
    (part: { mimeType: string }) => part.mimeType === "text/html"
  )?.body?.data;

  if (!body) {
    return null; // No HTML body found
  }

  // Decode base64url encoded body
  const decodedBody = atob(body.replace(/-/g, "+").replace(/_/g, "/"));

  // Extract unsubscribe link from the HTML body
  const match = decodedBody.match(
    /<a[^>]+href="([^"]+)"[^>]*>unsubscribe<\/a>/i
  );

  return match ? match[1] : null; // Return the link or null if not found
}

export async function unsubscribeUsingPostUrl(url: string) {
  const response = await fetch(url, { method: "POST" });

  if (!response.ok) {
    throw new Error(
      `Failed to unsubscribe using POST URL: ${response.status} ${response.statusText}`
    );
  }
  console.log(`Unsubscribed using POST URL: ${url}`);
}

export async function unsubscribeUsingMailTo(email: string) {
  // Get OAuth token
  const token = await getOAuthToken();

  // Create message
  const rawLines = [
    `To: ${email}`,
    "Subject: unsubscribe",
    'Content-Type: text/plain; charset="UTF-8"',
    "",
    "This message was automatically generated by Gmail Declutter.",
  ];
  const raw = rawLines.join("\r\n");

  // Encode message
  const encoded = btoa(encodeURIComponent(raw))
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");

  // Send message using Gmail API
  const response = await fetch(
    "https://gmail.googleapis.com/gmail/v1/users/me/messages/send",
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ raw: encoded }),
    }
  );

  if (!response.ok) {
    throw new Error(`Gmail API error: ${response.status} ${response.statusText}`);
  }
  console.log(`Unsubscribed using mailto: ${email}`);
}